In [8]:
import numpy as np

In [20]:
c=np.array([
    [1,2,3],
    [3,4,5],
    [6,7,8]
    
])
c

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
a=np.array([
    [1,2,3],
    [3,4,5],
    [6,7,8]
    
])

In [34]:
a[a>a.mean()]


array([5, 6, 7, 8])

In [37]:
a[(a>=2) & (a<6)]

array([2, 3, 3, 4, 5])

In [38]:
2 & 4

0

In [40]:
2 | 4

6